import pandas as pd
import os
import sys

try:
    import xlsxwriter
    import send2trash
except ModuleNotFoundError:
    print("The required packages are not installed. Installing the packages...")
    import subprocess

    required_packages = ["send2trash", "xlsxwriter"]
    for package in required_packages:
        subprocess.call([sys.executable, "pip", "install", package])
    print(
        "Download completed! condensing_excel_output.py will attempt to import the packages again. If error occurs, please run the script again."
    )
    import xlsxwriter
    import send2trash


# This script will condense all excel output generated by the data_exporter.py into one single excel sheet

# --- user input ---

working_directory = r"./LTLB data/formatted data/"
# --------------------


def consolidating_excel_files():
    """Consolidate all the excel files containing the summary stats into one excel file."""

    os.chdir(working_directory)
    count_file = 0

    for _ in os.listdir():
        if _.endswith(".xlsx"):
            count_file += 1
    if count_file > 1:

        row_number = 0
        data_file = []

        for file in os.listdir():

            if (
                file.endswith("xlsx")
                and not file.startswith("~$")
                and "Consolidated" not in file
            ):
                print(
                    f"Opening and exporting the data from {file} into consolidated excel..."
                )
                df = pd.read_excel(file)
                data_file.append(df)

        writer = pd.ExcelWriter("Consolidated stats.xlsx", engine="xlsxwriter")
        for data in data_file:
            data.to_excel(writer, sheet_name="Results", startrow=row_number)
            row_number += 10

        writer.save()
        print("Done!")
        for file in os.listdir():
            if file.endswith(".xlsx") and "Consolidated" not in file:
                print(f"Sending {file} into the recycle bin...")
                send2trash.send2trash(file)
    else:
        print(
            "There is only one xlsx file in this folder. The script will only work if more than one xlsx files are detected."
        )


consolidating_excel_files()
